name: Singularity Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        singularity_version:
          - '3.7.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Build Container
      env:
        SINGULARITY_RECIPE: Singularity
        OUTPUT_CONTAINER: container.sif
      run: |
       cd 1.0.0
       if [ -f "${SINGULARITY_RECIPE}" ]; then
           singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
       else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
           ls
       fi

       if [ -f ${OUTPUT_CONTAINER} ]; then
           echo "${OUTPUT_CONTAINER} image found."
       else
           echo "${OUTPUT_CONTAINER} image not found."
           exit 1
       fi
